import os
import glob
import argparse
import librosa
import numpy as np
import scipy.signal
import csv

def map_value(value, in_min, in_max, out_min=0, out_max=4095):
    """Maps a value from one range to the 0-4095 CV range."""
    if in_max == in_min:
        return 0
    normalized = (value - in_min) / (in_max - in_min)
    mapped = normalized * (out_max - out_min) + out_min
    return int(np.clip(mapped, out_min, out_max))

def main():
    parser = argparse.ArgumentParser(description="Generate 2D Corpus Header for MTM Workshop System.")
    parser.add_argument("folder", help="Path to the folder containing .wav samples")
    parser.add_argument("-d", "--downsample", type=int, default=1, 
                        help="Downsample factor (e.g., 2 reduces size by half)")
    parser.add_argument("-p", "--plot", action="store_true", 
                        help="Plot the mapped coordinates using matplotlib (lazy loaded)")
    # --- NEW: CSV Flag ---
    parser.add_argument("-c", "--csv", action="store_true", 
                        help="Export the mapped coordinates to a CSV file")
    
    args = parser.parse_args()
    folder_path = args.folder
    d_factor = args.downsample

    if not os.path.isdir(folder_path):
        print(f"Error: Folder '{folder_path}' not found.")
        return

    wav_files = glob.glob(os.path.join(folder_path, "*.[wW][aA][vV]"))

    if not wav_files:
        print(f"Error: No .wav files found in '{folder_path}'.")
        return
        
    print(f"Found {len(wav_files)} files. Analyzing (Pass 1)...")

    analyzed_data = []
    centroids = []
    energies = [] 

    # --- PASS 1: Analysis ---
    for file in wav_files:
        y, sr = librosa.load(file, sr=48000, mono=True)
        
        y, _ = librosa.effects.trim(y, top_db=40)
        if len(y) == 0:
            continue

        y = y / np.max(np.abs(y))
        
        current_n_fft = min(2048, len(y))
        current_hop = max(1, current_n_fft // 4)
        
        centroid = np.mean(librosa.feature.spectral_centroid(
            y=y, sr=sr, n_fft=current_n_fft, hop_length=current_hop
        ))
        energy = np.mean(librosa.feature.rms(
            y=y, frame_length=current_n_fft, hop_length=current_hop
        )) 
        
        centroids.append(centroid)
        energies.append(energy)
        analyzed_data.append({"file": file, "audio": y, "centroid": centroid, "energy": energy})

    min_c, max_c = min(centroids), max(centroids)
    min_e, max_e = min(energies), max(energies)

    print(f"Generating Header (Pass 2) with downsample factor: {d_factor}...")
    
    corpus_entries = []
    
    # We still collect this data for the plotter, even if we don't save the CSV
    csv_rows = [] 

    # --- PASS 2: Process and Stream to Disk ---
    with open("corpus_data.h", "w") as f:
        f.write("#pragma once\n#include <stdint.h>\n\n// --- AUTOGENERATED CORPUS DATA ---\n\n")

        for i, data in enumerate(analyzed_data):
            mapped_x = map_value(data["centroid"], min_c, max_c)
            mapped_y = map_value(data["energy"], min_e, max_e)
            
            file_basename = os.path.basename(data["file"])
            csv_rows.append([file_basename, mapped_x, mapped_y, data["centroid"], data["energy"]])
            
            if d_factor > 1:
                processed_audio = scipy.signal.decimate(data["audio"], d_factor, zero_phase=True)
            else:
                processed_audio = data["audio"]
            
            int_audio = np.int16(np.clip(processed_audio, -1.0, 1.0) * 32767)
            array_name = f"sample_{i:03d}_data"
            
            array_str = ", ".join(map(str, int_audio))
            f.write(f"const int16_t {array_name}[] = {{{array_str}}};\n")
            
            corpus_entries.append(f"    {{{mapped_x}, {mapped_y}, {array_name}, {len(int_audio)}}}")

        f.write("\nstruct CorpusItem {\n    int32_t x;\n    int32_t y;\n    const int16_t* data;\n    uint32_t length;\n};\n\n")
        f.write("const CorpusItem corpus[] = {\n" + ",\n".join(corpus_entries) + "\n};\n")
        f.write(f"const int NUM_SAMPLES = {len(analyzed_data)};\n")
        
    print(f"Success! Wrote corpus_data.h")

    # --- PASS 3: Optional CSV Writing ---
    if args.csv:
        csv_filename = "corpus_coordinates.csv"
        with open(csv_filename, "w", newline="") as csvfile:
            csvwriter = csv.writer(csvfile)
            csvwriter.writerow(["Filename", "Mapped_X", "Mapped_Y", "Raw_Centroid", "Raw_Energy"])
            csvwriter.writerows(csv_rows)
        print(f"Success! Wrote {csv_filename}")

    # --- PASS 4: Optional Plotting ---
    if args.plot:
        print("Generating visualization...")
        try:
            import matplotlib.pyplot as plt
        except ImportError:
            print("Error: matplotlib is not installed. Please run 'pip install matplotlib' to use the -p flag.")
            return

        x_vals = [row[1] for row in csv_rows]
        y_vals = [row[2] for row in csv_rows]

        plt.figure(figsize=(8, 8))
        plt.scatter(x_vals, y_vals, c='steelblue', alpha=0.7, edgecolors='black', s=50)

        plt.title(f"Corpus 2D Map ({len(x_vals)} Samples)", fontsize=14)
        plt.xlabel("Mapped X (Spectral Centroid: 0-4095)", fontsize=12)
        plt.ylabel("Mapped Y (RMS Energy: 0-4095)", fontsize=12)
        
        plt.xlim(-100, 4195)
        plt.ylim(-100, 4195)
        plt.grid(True, linestyle='--', alpha=0.5)
        
        print("Opening plot window. Close the window to exit the script.")
        plt.show()

if __name__ == "__main__":
    main()