import os
import glob
import argparse
import librosa
import numpy as np
import scipy.signal

def map_value(value, in_min, in_max, out_min=-2048, out_max=2047):
    """Maps a value from one range to the -2048 to 2047 CV range."""
    if in_max == in_min:
        return 0
    normalized = (value - in_min) / (in_max - in_min)
    mapped = normalized * (out_max - out_min) + out_min
    return int(np.clip(mapped, out_min, out_max))

def main():
    parser = argparse.ArgumentParser(description="Generate 2D Corpus Header for MTM Workshop System.")
    parser.add_argument("folder", help="Path to the folder containing .wav samples")
    parser.add_argument("-d", "--downsample", type=int, default=1, 
                        help="Downsample factor (e.g., 2 reduces size by half)")
    
    args = parser.parse_args()
    folder_path = args.folder
    d_factor = args.downsample

    if not os.path.isdir(folder_path):
        print(f"Error: Folder '{folder_path}' not found.")
        return

    wav_files = glob.glob(os.path.join(folder_path, "*.wav"))
    if not wav_files:
        print(f"Error: No .wav files found in '{folder_path}'.")
        return
        
    print(f"Found {len(wav_files)} files. Analyzing (Pass 1)...")

    analyzed_data = []
    centroids = []
    energies = [] # Swapped ZCR for Energy/Loudness for a better 2D spread

    # --- PASS 1: Analysis ---
    for file in wav_files:
        y, sr = librosa.load(file, sr=48000, mono=True)
        
        # Strip silence from beginning and end to save flash memory
        y, _ = librosa.effects.trim(y, top_db=40)
        
        if len(y) == 0:
            continue

        # Peak Normalization (make everything the same max volume)
        y = y / np.max(np.abs(y))
        
        # Feature Extraction
        centroid = np.mean(librosa.feature.spectral_centroid(y=y, sr=sr))
        energy = np.mean(librosa.feature.rms(y=y)) # RMS measures perceived loudness/body
        
        centroids.append(centroid)
        energies.append(energy)
        analyzed_data.append({"file": file, "audio": y, "centroid": centroid, "energy": energy})

    min_c, max_c = min(centroids), max(centroids)
    min_e, max_e = min(energies), max(energies)

    print(f"Generating Header (Pass 2) with downsample factor: {d_factor}...")
    
    corpus_entries = []

    # --- PASS 2: Process and Stream to Disk (Saves RAM) ---
    with open("corpus_data.h", "w") as f:
        f.write("#pragma once\n#include <stdint.h>\n\n// --- AUTOGENERATED CORPUS DATA ---\n\n")

        for i, data in enumerate(analyzed_data):
            mapped_x = map_value(data["centroid"], min_c, max_c)
            mapped_y = map_value(data["energy"], min_e, max_e)
            
            # Proper Anti-Aliased Downsampling
            if d_factor > 1:
                processed_audio = scipy.signal.decimate(data["audio"], d_factor, zero_phase=True)
            else:
                processed_audio = data["audio"]
            
            # Convert Float to full 16-bit Int (-32768 to 32767) for maximum fidelity
            int_audio = np.int16(np.clip(processed_audio, -1.0, 1.0) * 32767)
            
            array_name = f"sample_{i:03d}_data"
            
            # Fast string writing
            array_str = ", ".join(map(str, int_audio))
            f.write(f"const int16_t {array_name}[] = {{{array_str}}};\n")
            
            corpus_entries.append(f"    {{{mapped_x}, {mapped_y}, {array_name}, {len(int_audio)}}}")

        # Write the lookup table at the end
        f.write("\nstruct CorpusItem {\n    int32_t x;\n    int32_t y;\n    const int16_t* data;\n    uint32_t length;\n};\n\n")
        f.write("const CorpusItem corpus[] = {\n" + ",\n".join(corpus_entries) + "\n};\n")
        f.write(f"const int NUM_SAMPLES = {len(analyzed_data)};\n")
        
    print(f"Success! Wrote corpus_data.h")

if __name__ == "__main__":
    main()