import os
import glob
import argparse
import librosa
import numpy as np

def map_value(value, in_min, in_max, out_min=-2048, out_max=2047):
    """Maps a value from one range to the -2048 to 2047 CV range."""
    if in_max == in_min:
        return 0
    normalized = (value - in_min) / (in_max - in_min)
    mapped = normalized * (out_max - out_min) + out_min
    return int(np.clip(mapped, out_min, out_max))

def main():
    # 1. Setup Argument Parser for clean flag handling
    parser = argparse.ArgumentParser(description="Generate 2D Corpus Header for MTM Workshop System.")
    parser.add_argument("folder", help="Path to the folder containing .wav samples")
    parser.add_argument("-d", "--downsample", type=int, default=1, 
                        help="Downsample factor (e.g., 2 reduces size by half, drops every other sample)")
    
    args = parser.parse_args()
    folder_path = args.folder
    d_factor = args.downsample

    if not os.path.isdir(folder_path):
        print(f"Error: Folder '{folder_path}' not found.")
        return

    wav_files = glob.glob(os.path.join(folder_path, "*.wav"))
    
    if not wav_files:
        print(f"Error: No .wav files found in '{folder_path}'.")
        return
        
    print(f"Found {len(wav_files)} files. Analyzing (Pass 1)...")

    analyzed_data = []
    centroids = []
    zcrs = []

    # --- PASS 1: Analysis ---
    for file in wav_files:
        # Load audio at full 48kHz for the most accurate feature extraction
        y, sr = librosa.load(file, sr=48000, mono=True)
        
        centroid = np.mean(librosa.feature.spectral_centroid(y=y, sr=sr))
        zcr = np.mean(librosa.feature.zero_crossing_rate(y))
        
        centroids.append(centroid)
        zcrs.append(zcr)
        analyzed_data.append({"file": file, "audio": y, "centroid": centroid, "zcr": zcr})

    min_centroid, max_centroid = min(centroids), max(centroids)
    min_zcr, max_zcr = min(zcrs), max(zcrs)

    print(f"Generating Header (Pass 2) with downsample factor: {d_factor}...")
    
    header_content = """#pragma once
#include <stdint.h>

// --- AUTOGENERATED CORPUS DATA ---
"""
    corpus_entries = []

    # --- PASS 2: Downsample, Normalize, and Format ---
    for i, data in enumerate(analyzed_data):
        mapped_x = map_value(data["centroid"], min_centroid, max_centroid)
        mapped_y = map_value(data["zcr"], min_zcr, max_zcr)
        
        # Apply Downsampling Factor via numpy slicing
        # If d_factor is 1, it changes nothing. If 2, it takes every 2nd sample.
        processed_audio = data["audio"][::d_factor]
        
        # Convert Float to 12-bit Int (-2048 to 2047)
        int_audio = np.int16(processed_audio * 2047)
        
        array_name = f"sample_{i:03d}_data"
        array_str = ", ".join(map(str, int_audio))
        
        header_content += f"const int16_t {array_name}[] = {{{array_str}}};\n"
        corpus_entries.append(f"    {{{mapped_x}, {mapped_y}, {array_name}, {len(int_audio)}}}")

    header_content += "\nstruct CorpusItem {\n    int32_t x;\n    int32_t y;\n    const int16_t* data;\n    uint32_t length;\n};\n\n"
    header_content += "const CorpusItem corpus[] = {\n" + ",\n".join(corpus_entries) + "\n};\n"
    header_content += f"const int NUM_SAMPLES = {len(wav_files)};\n"

    with open("corpus_data.h", "w") as f:
        f.write(header_content)
        
    print(f"Success! Wrote corpus_data.h")

if __name__ == "__main__":
    main()